### ISSUE TITLE
git ignore 수정해주세요~~

### ISSUE THREAD

**Issue by della-padula** [dream7739/Study_iOS#1]
프로젝트를 열 수가 없어요.. project.pbxproj  파일이 ignore되어서 열 수가 없... ㅜㅜ

**Comment by dream7739** [comment]
gitignore파일 없는데 계속 프로젝트 파일이 ignore되요..ㅠㅠㅠ 올려놨어욤..

**Comment by dream7739** [comment]
알고보니 .gitignore_global 에 project.pbxproj가 들어있어서 계속 안올라가던거였어요...뒤늦은 깨달음ㅎㅋ....

**Comment by della-padula** [comment]
ㅋㅋㅋㅋㅋㅋ 잘하셨습니다
