### ISSUE TITLE
Button IBAction 대신 addTarget을 하신 이유가 있으신가요?

### ISSUE THREAD

**Issue by della-padula** [dream7739/Study_iOS#2]
https://github.com/dream7739/Study_iOS/blob/5964b4d4cb6ca85c552cd1d2a0a2fceaab6a5463/AddressSearchExample/AddressSearchExample/MainViewController.swift#L25

**Comment by dream7739** [comment]
별다른 이유는 없고..버튼을 cornerRadious변경하려고 outlet으로 빼서 addTarget으로 했습니당..

**Comment by della-padula** [comment]
아하 IBOutlet이랑 IBAction 둘다 함께 사용할 수 있어요~
